export const countries = [
    { key: "au", label: "Australia" },
    { key: "bd", label: "Bangladesh" },
    { key: "br", label: "Brazil" },
    { key: "ca", label: "Canada" },
    { key: "cn", label: "China" },
    { key: "fr", label: "France" },
    { key: "de", label: "Germany" },
    { key: "in", label: "India" },
    { key: "jp", label: "Japan" },
    { key: "mx", label: "Mexico" },
    { key: "ru", label: "Russia" },
    { key: "za", label: "South Africa" },
    { key: "gb", label: "United Kingdom" },
    { key: "us", label: "United States" },
  ];