export * from "./about";
export * from "./auth";
export { default as CompanyServices } from "./companyservices";
export * from "./explore";
export { default as Footer } from "./footer";
export { default as Header } from "./header";
export * from "./homepage";
export { default as Navbar } from "./navbar";
export * from "./shared";
export { default as SocialImages } from "./socialimages";
export { default as PrivacyPolicyContents } from "./privacypolicy";
export { default as TermsConditionsContents } from "./termsconditions";
export { default as CookiePolicyContents } from "./cookie-policy";
export { default as ReturnRefundContents } from "./returnrefund";
export { default as DeliveryContents } from "./delivery";
export { default as BlogContents } from "./blog";
export { default as YouMayAlsoLike } from "./youmayalsolike";
